export { default as Menu } from './menu/menu'
export { default as Home } from './home/home'
export { default as About } from './about/about'
export { default as Contact } from './contact/contact'
export { default as Store } from './store/store'
export { default as Blog } from './blog/blog'
export { default as CompareProduct } from './compare-product/compare-product'